In [2]:
import numpy as np

# Одномерные массивы (векторы)

## Создание массивов и тип данных в них

In [3]:
a=np.array([1,2,3,4,5,6,7])#из списка
print(a,type(a))

b=np.array((1.7,2,3,4,5.9,6,7))#из кортежа
print(b,type(b))

c=np.array((1,2,3,4,5,6,'7'))#из кортежа
print(c,type(a))


[1 2 3 4 5 6 7] <class 'numpy.ndarray'>
[1.7 2.  3.  4.  5.9 6.  7. ] <class 'numpy.ndarray'>
['1' '2' '3' '4' '5' '6' '7'] <class 'numpy.ndarray'>


**Numpy массивы приводит данные к одному типу. По умолчанию все значения приводятся к типу float или str. Тип данных можно узнать с помощью атрибута dtype:**


In [4]:
print(a.dtype,b.dtype,c.dtype)

int32 float64 <U11


**Если мы хотим задать свой тип, к которому нужно привести данные, это можно сделать сразу с помощью аргкмента dtype или используя функцию astype()**

In [5]:
c=np.array((1.2,4,'3'),dtype=int)
print(c)

print(b.astype(int))

[1 4 3]
[1 2 3 4 5 6 7]


**Можно создавать массивы, заполненные нулями(np.zeros) или единицами(np.ones). Часто лучше сначала создать такой массив, а потом присваивать значения его элементам:**

In [6]:
z=np.zeros(3) 
o=np.ones(3,dtype=np.int64)
print(z)
print(o)

[0. 0. 0.]
[1 1 1]


**Если нужно создать массив, заполненный нулями, длины и типа другого массива, то можно использовать конструкцию:**

In [7]:
np.zeros_like(a)

array([0, 0, 0, 0, 0, 0, 0])

**Можно создавать массивы с постоянным шагом с помощью функции *linspace(x,y,z)*, где x-начальное значение, y-конечное значение, а z-число элементов:**

In [8]:
l=np.linspace(0,10,5)
print(l)

[ 0.   2.5  5.   7.5 10. ]


## Размер


**ndim-возвращает размерность массива ndrray(a=np.array([1,2,3,4,5,6,7])**

In [9]:
a.ndim

1

**shape-возвращает число элементов массива с помощью кортежа натуральных чисел, показывающем длину массива по каждой оси. Число элементов в shape равно значению в ndim:**

In [10]:
a.shape

(7,)

**size-число всех элементов массива. Равно произведению всех элементов атрибута shape:**

In [11]:
a.size

7

**len - функция определяет количество элементов в объекте. Если a.ndim больше 1, то выводит количество столбцов:**

In [12]:
len(a)

7

## Индексация


**Получить элементы массива можно по индексу:**

In [13]:
a[0]

1

**Также можно использовать срезы:**

In [14]:
a[2:5] #берутся элементы с индексами 2,3,4 т.e. [a[2], a[3], a[4]]

array([3, 4, 5])

In [15]:
a[:2] #берутся элементы с индексами строго меньше 2, т.е. [a[0],a[1]]

array([1, 2])

In [16]:
a[2:] #берутся элементы большими или равными 2 т.е. [a[2],a[3],a[4],...,a[n]]

array([3, 4, 5, 6, 7])

In [17]:
a[-1] #берется последний элемент

7

**Диапозон с шагом 2:**

In [18]:
a[0:5:2] #a[x:y:z] где x-начальное значение, y-последнее заданное значение, а z-шаг

array([1, 3, 5])

**Массивы можно изменять, задавая значение:**

In [19]:
a[1]=9
print(a)

[1 9 3 4 5 6 7]


**Чтобы скопировать данные данные массива, нужно использовать метод copy()**

In [20]:
d=a.copy()
d[2]=9
print(a)
print(d)

[1 9 3 4 5 6 7]
[1 9 9 4 5 6 7]


**Массивы можно использовать в for циклах**

In [21]:
for i in a:
    print(i)

1
9
3
4
5
6
7


## Нахождение уникальных значений

**Функция unique() находит уникальные элементы массива и возвращает их в отсортированном массиве**

In [22]:

np.unique(d,return_counts=True)#return_counts=True кол-во вхождений

(array([1, 4, 5, 6, 7, 9]), array([1, 1, 1, 1, 1, 2], dtype=int64))

## Математические операции над одномерными ndarray-массивами

**Зададим два одномерных массива**

In [23]:
p=np.array([0,-1,4,3,-2])
q=np.array([2,4,-2,1,3])

**Арифметические операции проводятся поэлементно**

In [24]:
print(p+q)  #или np.add(p,q)
print(p-q)
print(p*q)
print(p/q)
print(p**2)

print(p+1,q-1) #можно прибавлять скаляр

[2 3 2 4 1]
[-2 -5  6  2 -5]
[ 0 -4 -8  3 -6]
[ 0.         -0.25       -2.          3.         -0.66666667]
[ 0  1 16  9  4]
[ 1  0  5  4 -1] [ 1  3 -3  0  2]


**Математические функции**

In [25]:
print(np.sin(q))
print(np.sqrt(q))
print(np.exp(q))
print(np.log(q))
print(np.tan(q))

print('e=',np.e, 'pi=',np.pi) 

[ 0.90929743 -0.7568025  -0.90929743  0.84147098  0.14112001]
[1.41421356 2.                nan 1.         1.73205081]
[ 7.3890561  54.59815003  0.13533528  2.71828183 20.08553692]
[0.69314718 1.38629436        nan 0.         1.09861229]
[-2.18503986  1.15782128  2.18503986  1.55740772 -0.14254654]
e= 2.718281828459045 pi= 3.141592653589793


<ipython-input-25-f08020d9b584>:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(q))
<ipython-input-25-f08020d9b584>:4: RuntimeWarning: invalid value encountered in log
  print(np.log(q))


**Сумма, произведение (всех элементов массива), максимальный, минимальный элемент, среднее и среднеквадратичное отклонение (p=np.array([0,-1,4,3,-2])):**

In [26]:
p.sum(), p.prod(),     p.max(),      p.min(),     p.mean(), p.std()
#cумма   произведение  максимальное  минимальное  среднее   среднеквадратичное

(4, 0, 4, -2, 0.8, 2.3151673805580453)

**Сравнение дают булевые массивы:**

In [27]:
print(p<q)
print(p==q)
print(q>5)

[ True  True False False  True]
[False False False False False]
[False False False False False]


## Сортировка и изменение

**Сортировка**

In [28]:
np.sort(p)

array([-2, -1,  0,  3,  4])

**Объединение**

In [29]:
np.append(p,[1,3,2]) # выводит первый массив, добавляя новые элементы в конец

array([ 0, -1,  4,  3, -2,  1,  3,  2])

In [30]:
np.append(p,q) #соединение двух массивов

array([ 0, -1,  4,  3, -2,  2,  4, -2,  1,  3])

**Удаление(p=np.array([0,-1,4,3,-2]))**

In [31]:
np.delete(p,[0,2]) #удаляет элементы по индексу

array([-1,  3, -2])

**Вставка**

In [32]:
np.insert(p,2,[-5,11]) #в вектор р на место с индексом 2 вставить элементы 

array([ 0, -1, -5, 11,  4,  3, -2])

**Функция np.dot(как и метод a.dot), вычисляет скалярное произведение векторов, а также произведение матриц**

In [33]:
scalar=p.dot(q)
print(p)
print(q)
print(scalar)

[ 0 -1  4  3 -2]
[ 2  4 -2  1  3]
-15


# Двумерные массивы (матрицы)

## Создание,тип

In [34]:
A=np.array([[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]])
print(A)

B=np.array([[0.0,-1.0],[1.0,0.0]])
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 0. -1.]
 [ 1.  0.]]


In [68]:
A.dtype,B.dtype

(dtype('int32'), dtype('float64'))

**Единичная матрица**

In [69]:
I=np.eye(3,4)#(cтолбцы, строки)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


**Размерномть**

In [75]:
print("Размерность: {}" .format(A.ndim)) 
print('Форма:{}' .format(A.shape))
print('Общее количество элементов:{}'.format(A.size))   #A.ndim сколькомерный

Размерность: 2
Форма:(3, 4)
Общее количество элементов:12


**Можно растянуть в одномерный массив:**

In [76]:
B.ravel()

array([ 0., -1.,  1.,  0.])

**Или при помощи reshape:**

In [79]:
B.reshape(4)

array([ 0., -1.,  1.,  0.])

**Можно из одномерного сделать двумерный:**

In [81]:
C=np.linspace(0,5,6) #создание массива(начальный элемент, конечный элемент, количество элементов)
print(C)

[0. 1. 2. 3. 4. 5.]


In [82]:
C.shape

(6,)

In [83]:
C.shape=2,3
print(C)

[[0. 1. 2.]
 [3. 4. 5.]]


**Или с помщью reshape()**

In [86]:
C.reshape(2,3)

array([[0., 1., 2.],
       [3., 4., 5.]])

In [44]:
T=np.linspace(1,20,9)
T.reshape(3,3)

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

## Индексация

**Получение элемента массива[строка, столбец]**

In [93]:
A[0,1], A[2,2] #A=np.array([[1,2,3,4],
                   #[5,6,7,8],
                   #[9,10,11,12]])

(2, 11)

**Строка**

In [94]:
A[0]

array([1, 2, 3, 4])

**Столбец**

In [95]:
A[:,0]

array([1, 5, 9])

**Срезы (подматрицы)**

In [100]:
A[1:,:3] #[строка:, :столбец]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [103]:
A[2:,:2]

array([[ 9, 10]])

In [101]:
A[1:3,2:4]

array([[ 7,  8],
       [11, 12]])

**Цикл по строкам**

In [104]:
for row in B:
    print(row)

[ 0. -1.]
[1. 0.]


## Математические операции над двумерными ndarray-массивами


In [105]:
A1=np.array([[0,1],
            [2,3],
            [4,5]])
A2=np.array([[6,7],
            [8,9],
            [10,11]])

In [106]:
print(A1+A2)#сложение
print(np.dot(A1,-1))#умножение на число
print(A1.T)#Транспонирование или так: A1.transpose()
print(A2.dot(A1.T))#Умножение матриц способ №1

[[ 6  8]
 [10 12]
 [14 16]]
[[ 0 -1]
 [-2 -3]
 [-4 -5]]
[[0 2 4]
 [1 3 5]]
[[ 7 33 59]
 [ 9 43 77]
 [11 53 95]]


In [107]:
print(A2@(A1.T))#умножение матриц способ №2

[[ 7 33 59]
 [ 9 43 77]
 [11 53 95]]


**Cуммы элементов:**

In [108]:
print(A1.sum()) #сумма всех элементов
print(A1.sum(axis=0)) #Суммы столбцов
print(A1.sum(axis=1)) #Cуммы строк

15
[6 9]
[1 5 9]


**Аналагично работают prod, max, min и т.д**

In [109]:
print(A2.max())
print(A2.max(axis=0))
print(A2.min(axis=1))

11
[10 11]
[ 6  8 10]


**Можно вычислять понятия из линейной алгебры:**

In [115]:
D=np.array([[0,1,1],
           [2,3,3],
           [4,5,6]])
print(np.trace(D)) #след - сумма диагональных элементов
print(np.linalg.det(D)) #определитель
print(np.linalg.matrix_rank(D)) #ранг
print(np.linalg.inv(D))#обращение к матрице

9
-2.0
3
[[-1.5  0.5  0. ]
 [ 0.   2.  -1. ]
 [ 1.  -2.   1. ]]


# Графическая визуализация данных